# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
import sys, gambar

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1139, 650)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1141, 651))
        self.frame.setStyleSheet("background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(450, 50, 241, 81))
        self.label.setStyleSheet("image: url(:/newPrefix/gambar/pendidikan.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(380, 160, 381, 31))
        self.label_2.setStyleSheet("font-weight: 500;\n"
"font-size: 25px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(410, 620, 331, 20))
        self.label_3.setStyleSheet("margin: auto;")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(380, 210, 381, 51))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 280, 381, 51))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(380, 350, 381, 51))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(380, 420, 381, 51))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 490, 181, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border-radius: 5px;\n"
"color: white;\n"
"font-weight: 200;\n"
"font-size: 15px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 490, 181, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-radius: 5px;\n"
"color: white;\n"
"font-weight: 200;\n"
"font-size: 15px;")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Pendaftaran Akun Peserta Didik"))
        self.label_3.setText(_translate("Form", "Developed By Alif Rizky Prasetya @2024"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Username (Nama Lengkap)"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Email"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Password"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Konfirmasi Password"))
        self.pushButton_2.setText(_translate("Form", "Daftar"))
        self.pushButton_3.setText(_translate("Form", "Masuk"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())